spring:
  application:
    name: git-it
  mongodb:
    host: ${MONGODB_HOST:localhost}
    port: ${MONGODB_PORT:27017}
    database: ${MONGODB_DATABASE:gitit}
    username: ${MONGODB_USERNAME:gitit}
    password: ${MONGODB_PASSWORD:gitit1234}
    authentication-database: admin
  data:
    mongodb:
      auto-index-creation: true

jwt:
  secret: ${JWT_SECRET:verylongsecretkeyfordevelopmentenvironmentonly}
  access_token:
    expiration_days: 30 # 1달
  refresh_token:
    expiration_days: 90 # 3달

oauth:
  google:
    client-id: ${OAUTH_GOOGLE_CLIENT_ID:google-client-id}
  apple:
    client-id: ${OAUTH_APPLE_CLIENT_ID:apple-client-id}
