name: Backend CI

on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: action checkout
        uses: actions/checkout@v4

      - name: Auto assign
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto_assign.yml'

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Lint with Gradle
        run: ./gradlew ktlintCheck detekt

      - name: Build with Gradle
        run: ./gradlew test bootJar
